
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  # - id: check-merge-conflict
  # - id: check-symlinks

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    # additional_dependencies:
    # - flake8-bugbear
    # - flake8-comprehensions
    # - flake8-tidy-imports

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v1.8.0"
  hooks:
    - id: mypy
      args: [./pool_workers, ./tests]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.10.1
  hooks:
    - id: pyupgrade
      args: [--py38-plus]
