name: Linting (flake8 & mypy)

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
      - "main"
    tags:
      - "*"
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Get the repo!
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Use Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Linting (flake8 & mypy)
        run: |
          # This will run flake8 & mypy
          poetry run make lint
